spring:
  application:
    name: user-management-api
  datasource:
    url: jdbc:mysql://localhost:3306/my_auth_db
    username: root
    password: abc123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 900000

security:
  session-timeout: 900
  max-login-attempts: 5
  account-lock-duration: 1800
